# Jekyll Configuration for Graduate Advice Hub
title: Graduate Advice Hub for Greeks
description: A website that aims to connect prospective and current Greek graduate students with valuable advice, resources, and a community of researchers.
url: "https://gradadvice.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

# Collections for organizing content
collections:
  people:
    output: true
    permalink: /people/:title/

# Navigation
header_pages:
  - index.md
  - about.md
  - people.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md
  - PROFILE_IMAGES_GUIDE.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - node_modules/
  - .DS_Store
