# Jekyll Configuration for PhD Advice Hub
title: PhD Advice Hub
description: A directory platform connecting PhD students, researchers, and academics
url: "https://stogiannidis.github.io"
baseurl: "/phd-advice-hub"

# Build settings
markdown: kramdown
theme: minima

# Collections for organizing content
collections:
  people:
    output: true
    permalink: /people/:path/

# Navigation
header_pages:
  - index.md
  - about.md
  - people.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - node_modules/
  - .DS_Store
